Repository MichaIng/DietPi-Website, pull requests merged in 2021-05, with the labels that each got.

#103 Add DietPi v7.2 Beta slide
  index.html
Labels: correction

#104 Release week 20
  index.html
Labels: release

#107 Add Brave Rewards donate button
  contribute.html
Labels: extension

#111 Release week 21 (DietPi v7.2 release)
  .wordlist.txt
  404.html
  contribute.html
  index.html
Labels: release
