Repository MichaIng/DietPi-Website, pull requests merged in 2021-07, with the labels that each got.

#129 Initial stats & comparison page draft
  contribute.html
  css/style.css
  dietpi-software.html
  images/stats/armbian.png
  images/stats/commands.svg
  images/stats/debian.svg
  images/stats/raspberrypios.svg
  index.html
  stats.html
Labels: new content

#136 Release week 28
  contribute.html
  css/style.css
  dietpi-software.html
  images/stats/armbian.png
  images/stats/commands.svg
  images/stats/debian.svg
  images/stats/raspberrypios.svg
  index.html
  stats.html
Labels: release

#137 Release week 29 (DietPi v7.4)
  index.html
Labels: release

#139 small updates to banner (version 7.4)
  index.html
Labels: enhancement
