Repository MichaIng/DietPi-Website, pull requests merged in 2021-08, with the labels that each got.

#142 Switch to GPU accelerated translate animation
  contribute.html
  css/jquery.cslider.css
  css/style.css
  dietpi-software.html
  index.html
  js/app.js
  js/jquery.cslider.js
  stats.html
Labels: performance

#143 Release week 30.2
  contribute.html
  css/jquery.cslider.css
  css/style.css
  dietpi-software.html
  index.html
  js/app.js
  js/jquery.cslider.js
  sitemap.xml
  stats.html
Labels: release

#144 Release week 31
  js/jquery.cslider.js
Labels: release

#147 Switch to own MixItUp fork with removed polyfills
  deploy.bash
Labels: performance

#146 Adjust Brave Rewards link and portfolio frame style
  contribute.html
Labels: enhancement, contribute.html

#148 Correct website navigation bar contents
  contribute.html
  dietpi-software.html
  index.html
  stats.html
Labels: correction

#149 Update RPi download links to Bullseye images
  index.html
Labels: index.html

#150 Release week 32
  contribute.html
  deploy.bash
  dietpi-software.html
  index.html
  stats.html
Labels: release

#151 Release week 33.1
  index.html
Labels: release

#153 Release week 33.2
  index.html
Labels: release
