Repository MichaIng/DietPi-Website, pull requests merged in 2022-03, with the labels that each got.

#200 Add Proxmox image to download page
  images/sbc_images/proxmox.svg
  index.html
Labels: extension

#203 Add ESXi/vSphere appliance to download page
  .wordlist.txt
  index.html
Labels: index.html, extension

#204 Update slider for v8.2 release
  index.html
Labels: index.html

#205 Release week 9
  .wordlist.txt
  images/sbc_images/proxmox.svg
  index.html
Labels: release

#207 Forward to current DietPi automation documentation
  index.html
Labels: correction, index.html

#208 Release week 11
  .github/workflows/main.yml
  css/style.css
  images/sbc_images/proxmox.svg
  index.html
Labels: release

#209 Add DietPi v8.3 Beta to slider
  .github/workflows/main.yml
  .wordlist.txt
  css/style.css
  index.html
Labels: release
