Repository MichaIng/DietPi-Website, pull requests merged in 2023-12, with the labels that each got.

#304 Update .wordlist.txt
  .wordlist.txt
Labels: correction

#297 Change contribute to donate and add logos for donation buttons!
  contribute.html
  css/style.css
  dietpi-software.html
  images/contribute/american-express.svg
  images/contribute/discover.svg
  images/contribute/mastercard.svg
  images/contribute/patreon.svg
  images/contribute/paypal.svg
  images/contribute/visa.svg
  index.html
  sitemap.xml
  stats.html
Labels: enhancement

#303 Java mono git added to software list
  .wordlist.txt
  dietpi-software.html
  images/dietpi-software/git-logo.svg
  images/dietpi-software/java-logo.svg
  images/dietpi-software/mono-logo.svg
Labels: dietpi-software.html, extension

#306 Add DietPi v8.25 release slide
  index.html
Labels: release

#307 Release week 51
  .github/workflows/main.yml
  .wordlist.txt
  contribute.html
  css/style.css
  dietpi-software.html
  images/contribute/american-express.svg
  images/contribute/discover.svg
  images/contribute/mastercard.svg
  images/contribute/patreon.svg
  images/contribute/paypal.svg
  images/contribute/visa.svg
  images/dietpi-software/Go-Logo1.png
  images/dietpi-software/git-logo.svg
  images/dietpi-software/java-logo.svg
  images/dietpi-software/microblogpub-logo.png
  images/dietpi-software/microblogpub-screenshot-small.jpg
  images/dietpi-software/mono-logo.svg
  images/dietpi-software/openhab-screenshot-small.jpg
  images/dietpi-software/vscodium-logo.png
  images/sbc_images/asustinkerboard2.jpg
  images/sbc_images/rock5a.jpg
  index.html
  sitemap.xml
  stats.html
Labels: release
