Repository MichaIng/DietPi-Website, pull requests merged in 2023-09, with the labels that each got.

#290 Move to xz-compressed images
  index.html
Labels: correction, index.html

#291 Add SHA256 and signature download links
  .wordlist.txt
  css/style.css
  index.html
Labels: extension

#288 Update stats on contribute page, remove brave rewards button
  contribute.html
Labels: correction

#292 Release week 38
  .wordlist.txt
  README.md
  contribute.html
  css/style.css
  deploy.bash
  index.html
Labels: release
