Repository MichaIng/DietPi-Website, pull requests merged in 2024-05, with the labels that each got.

#326 Add ROCK 4C Plus to download page
  index.html
Labels: index.html, extension

#327 Add DietPi Beta v9.4 slide
  .wordlist.txt
  index.html
Labels: index.html, release

#328 Release week 20
  .wordlist.txt
  images/contribute/american-express.svg
  images/dietpi-software/java-logo.svg
  images/dietpi-software/mono-logo.svg
  images/dietpi-software/openhab-logo.svg
  images/sbc_images/nanopct6.jpg
  images/sbc_images/nanopir5c.jpg
  images/sbc_images/nanopir6c.jpg
  images/sbc_images/orangepi3b.jpg
  images/sbc_images/orangepi3lts.jpg
  images/sbc_images/orangepizero2w.jpg
  images/sbc_images/orangepizero3.jpg
  images/sbc_images/radxazero3.jpg
  images/sbc_images/raspberrypi5.jpg
  images/sbc_images/star64.jpg
  index.html
Labels: release

#330 Update stats page
  .github/workflows/main.yml
  .wordlist.txt
  index.html
  stats.html
Labels: stats.html

#331 Zero 2 added to the download box description
  index.html
Labels: extension

#332 Another little comparison update
  index.html
  stats.html
Labels: release

#333 Fix labels for Debian x86_64 comparison
  stats.html
Labels: release
