Repository MichaIng/DietPi-Website, pull requests merged in 2024-01, with the labels that each got.

#308 Release week 3
  index.html
Labels: release

#311 Extend some text to the contribution options
  contribute.html
Labels: extension

#310 Correct linking to DietPi tools
  index.html
Labels: correction

#312 Rearrange header
  404.html
  contribute.html
  dietpi-software.html
  index.html
  maintenance.html
  stats.html
Labels: enhancement

#314 Headline fix
  dietpi-software.html
  index.html
  stats.html
Labels: correction

#313 Release week 4
  404.html
  contribute.html
  deploy.bash
  dietpi-software.html
  index.html
  maintenance.html
  stats.html
Labels: release

#315 Release week 5
  maintenance.html
Labels: release
