Repository MichaIng/DietPi-Website, pull requests merged in 2025-02, with the labels that each got.

#350 Links to RISC-V changed from Sid to Trixie
  index.html
Labels: correction

#351 Release week 6
  contribute.html
  index.html
Labels: release

#352 Update Raspberry Pi downloads
  index.html
Labels: index.html, release

#353 Release week 7
  deploy.bash
  index.html
Labels: release

#354 Release week 8
  .github/workflows/main.yml
  index.html
Labels: release

#356 Clock frequency NanoPi R2S and NEO3 corrected
  index.html
Labels: correction
